export const CONSTANTS = {
    LOGIN_SUCCESS: "Login request successfully.",
    USER_NOT_EXIST: "User does not exists.",
    INCORRECT_EMAIL_PASSWORD: "Invalid Email ID or password",
    INCORRECT_PASSWORD: "Password is incorrect",
    EMAIL_ID_NOT_EXIST: "Email id does not exists.",
    PROFILE_UPDATED_SUCCESSFULLY: "Profile updated successfully.",
    EMAIL_ALREADY_EXIST: "Email address already exists.",
    SUCCESS: "Success",
    FAILED: "Failed",
    INVALID_OTP: "Invalid OTP",
    USER_NOT_FOUND: "User not found.",
    AUTHENTICATION_FAILED: "Invalid credentials",
    REQUIRED_FIELDS_ARE_MISSING: "Required fields are missing.",
    SOMETHING_WENT_WRONG: "Something went wrong! Please try again.",
    INVALID_TOKEN: "Token is not valid.",
    ALREADY_EXISTS: "Already Exists! please try again.",
    EMAIL_ALREADY_EXISTS: "Email already exists.",
    USERNAME_ALREADY_EXISTS: "Username already exists.",
    REGISTER_SUCCESS: "User registered successfuly."
}

export const CODES = {
    OK: 200,
    CREATED: 201,
    ACCEPTED: 202,
    NO_CONTENT: 204,
    MOVED_PERMANENTLY: 301,
    FOUND: 301,
    NOT_MODIFIED: 304,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    METHOD_NOT_ALLOWED: 405,
    NOT_ACCEPTABLE: 406,
    INTERNAL_SERVER_ERROR: 500,
    NOT_IMPLEMENTED: 501,
    ALREADY_EXIST: 409,
    NOT_VERIFIED: 505,
    SESSION_EXPIRE: 440,
};
